// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbgnJxDRDZIERBDU9vI-bfR0FqpI4u2pY',
    appId: '1:572590140048:web:c99525bc37e6605a03c615',
    messagingSenderId: '572590140048',
    projectId: 'subwaycongestion',
    authDomain: 'subwaycongestion.firebaseapp.com',
    storageBucket: 'subwaycongestion.appspot.com',
    measurementId: 'G-YQ6HC2PEFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGfiTr6CyHIZNQ_h1E2MiG8XIpSO2-K0M',
    appId: '1:572590140048:android:09279de052cf206603c615',
    messagingSenderId: '572590140048',
    projectId: 'subwaycongestion',
    storageBucket: 'subwaycongestion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZA9td7D0J3G6RLQJc0pyy56BcwDvrM9E',
    appId: '1:572590140048:ios:393ee06a0b86fb6703c615',
    messagingSenderId: '572590140048',
    projectId: 'subwaycongestion',
    storageBucket: 'subwaycongestion.appspot.com',
    iosClientId: '572590140048-qonie1957ub9sntrkprbfe5hns8jm1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.subwayCongestion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZA9td7D0J3G6RLQJc0pyy56BcwDvrM9E',
    appId: '1:572590140048:ios:393ee06a0b86fb6703c615',
    messagingSenderId: '572590140048',
    projectId: 'subwaycongestion',
    storageBucket: 'subwaycongestion.appspot.com',
    iosClientId: '572590140048-qonie1957ub9sntrkprbfe5hns8jm1pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.subwayCongestion',
  );
}
